blue_chart_app/urls.py
"""
Created on Sat Dec 19 13:50:53 2020

@author: Mayuko
"""


from django.urls import path
from . import views


app_name = 'blue_chart_app'

urlpatterns = [
    
    path('', views.chapter_view.chapter_list, name='chapter_list'),
    path('siteUser/register', views.siteUser_view.siteUser_register, name='siteUser_register'),
    path('siteUser/logout', views.siteUser_view.siteUser_logout, name='siteUser_logout'),
    path('siteUser/login', views.siteUser_view.siteUser_login, name='siteUser_login'),
    path('siteUser/reference_user/login', views.siteUser_view.reference_user_login_view, name='reference_user_login'),
    path('siteUser/reference_user/logout', views.siteUser_view.reference_user_logout_view, name='reference_user_logout'),
    path('chapter/list', views.chapter_view.chapter_list, name='chapter_list'),
    path('section/list/<int:chapter_id>/', views.section_view.section_list_view, name='section_list'),
    path('problem_group/list/<int:section_id>/', views.problem_group_view.problem_group_list_view, name='problem_group_list'),
    path('problem/list/<int:problem_group_id>/', views.problem_view.problem_list_view, name='problem_list'),
    path('problem/search', views.problem_view.problem_search_view, name='problem_search'),
    path('problem/show/<int:problem_id>/', views.problem_view.problem_show_view, name='problem_show'),
    path('problem/list_with_cause_tag/<int:cause_tag_id>/<int:section_id>/', views.problem_view.problem_list_with_cause_tag_view, name='problem_list_with_cause_tag'),
    path('evaluate/register/<int:problem_id>/', views.evaluate_view.evaluate_register_view, name='evaluate_register'),
    path('evaluate/delete/<int:evaluate_id>/', views.evaluate_view.evaluate_delte_view, name='evaluate_delete'),
    path('comment_for_evaluate/register/<int:evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_register_view, name='comment_for_evaluate_register'),
    path('comment_for_evaluate/update/<int:comment_for_evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_update_view, name='comment_for_evaluate_update'),
    path('comment_for_evaluate/delte/<int:comment_for_evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_delete_view, name='comment_for_evaluate_delete'),
    path('evaluation/suggest/', views.evaluation_tag_view.evaluation_tag_suggest_view, name='evaluation_tag_suggest'),
    path('evaluation/search/', views.evaluation_tag_view.evaluation_tag_search_view, name='evaluation_tag_search'),
    path('answer/register/<int:problem_id>/', views.answer_view.answer_register_view, name='answer_register'),
    path('answer/update/<int:answer_id>/', views.answer_view.answer_update_view, name='answer_update'),
    path('answer/list_with_problem/<int:problem_id>/', views.answer_view.answer_list_with_problem_view, name='answer_list_with_problem'),
    path('answer/list_with_cause_tag/<int:problem_id>/<int:cause_tag_id>/<int:section_id>/', views.answer_view.answer_list_with_cause_tag_view, name='answer_list_with_cause_tag'),
    path('answer/all_list/', views.answer_view.answer_all_list_view, name='answer_all_list'),
    path('answer/show/<int:answer_id>/', views.answer_view.answer_show_view, name='answer_show'),
    path('answer/delete/<int:answer_id>/', views.answer_view.answer_delete_view, name='answer_delete'),
    path('commet_for_answer/register/<int:answer_id>/', views.comment_for_answer_view.comment_for_answer_register_view, name='comment_for_answer_register'),
    path('comment_for_answer/update/<int:comment_for_answer_id>/', views.comment_for_answer_view.comment_for_answer_update_view, name='comment_for_answer_update'),
    path('comment_for_answer/delete/<int:comment_for_answer_id>/', views.comment_for_answer_view.comment_for_answer_delete_view, name='comment_for_answer_delete'),
    path('answer_photo/register/<int:answer_id>/', views.answer_photo_view.answer_photo_register_view, name='answer_photo_register'),
    path('answer_photo/delete/<int:answer_photo_id>/', views.answer_photo_view.answer_photo_delete_view, name='answer_photo_delete'),
    path('comment_for_answer_photo/register/<int:answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_register_view, name='comment_for_answer_photo_register'),
    path('comment_for_answer_photo/update/<int:comment_for_answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_update_view, name='comment_for_answer_photo_update'),
    path('comment_for_answer_photo/delete/<int:comment_for_answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_delete_view, name='comment_for_answer_photo_delete'),
    path('cause_tag/list/<int:section_id>/', views.cause_tag_view.cause_tag_list_view, name='cause_tag_list'),
    path('cause_tag/graph/', views.cause_tag_view.cause_tag_graph, name='cause_tag_graph'),
    path('cause_tag/connects_count/', views.cause_tag_view.connects_count, name='connects_count'),
    path('connect/register/<int:answer_id>/', views.connect_view.connect_register_view, name='connect_register'),
    path('connect/overcome_flag_change/<int:connect_id>/', views.connect_view.connect_is_overcome_change_view, name='connect_is_overcome_change'),
    path('connect/delete/<int:connect_id>/', views.connect_view.connect_delete_view, name='connect_delete'),
    path('comment_for_connect/register/<int:connect_id>/', views.comment_for_connect_view.comment_for_connect_register_view, name='comment_for_connect_register'),
    path('comment_for_connect/update/<int:comment_for_connect_id>/', views.comment_for_connect_view.comment_for_connect_update_view, name='comment_for_connect_update'),
    path('comemnt_for_connect/delete/<int:comemnt_for_connect_id>/', views.comment_for_connect_view.comment_for_connect_delete_view, name='comment_for_connect_delete'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('blue_chart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

blue_chart_app/models/answer.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .problem import Problem
from .correct_situation import CorrectSituation
from .connect import Connect
from django.core.exceptions import ObjectDoesNotExist


class Answer(models.Model):

    correct_situation = models.ForeignKey(
        CorrectSituation, on_delete=models.CASCADE, null=True
    )
    solve_plan_date = models.DateTimeField(default=timezone.now, blank=True)
    solve_date = models.DateTimeField(default=timezone.now, null=True)
    actual_time = models.IntegerField(null=True)
    student = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def is_overcome_with_cause_tag(self, cause_tag_id):
        try:
            connect = Connect.objects.get(answer__id=id, cause_tag__id=cause_tag_id)
            return connect.is_overcome

        except ObjectDoesNotExist:

            return -1

blue_chart_app/models/answer_photo.py
from django.db import models
from .siteUser import SiteUser
from .answer import Answer
from django.utils import timezone


class AnswerPhoto(models.Model):

    image = models.ImageField(upload_to="images", blank=True, null=True)
    upload_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, related_name="answer_photo"
    )
    uploaded_at = models.DateTimeField(default=timezone.now, null=True)

blue_chart_app/models/cause_tag.py
from django.db import models
from .type import Type


class CauseTag(models.Model):

    content = models.CharField(max_length=255, null=True)
    cause_type = models.ForeignKey(
        Type, related_name="cause", on_delete=models.CASCADE, null=True
    )

blue_chart_app/models/chapter.py
from django.db import models
from .subject import Subject


class Chapter(models.Model):

    name = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blue_chart_app/models/comment_for_answer.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .answer import Answer


class CommentForAnswer(models.Model):

    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, null=True, related_name="comments_for_answer"
    )

blue_chart_app/models/comment_for_answer_photo.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .answer import Answer
from .answer_photo import AnswerPhoto


class CommentForAnswerPhoto(models.Model):
    
    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    answer_photo = models.ForeignKey(AnswerPhoto, on_delete=models.PROTECT, null=True, related_name='comments_for_answer_photo')

blue_chart_app/models/comment_for_connect.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .connect import Connect
from .answer_photo import AnswerPhoto


class CommentForConnect(models.Model):

    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    connect = models.ForeignKey(
        Connect, on_delete=models.CASCADE, related_name="comments_for_connect"
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

blue_chart_app/models/comment_for_evaluate.py
from django.db import models
from .evaluate import Evaluate
from .siteUser import SiteUser
from django.utils import timezone


class CommentForEvaluate(models.Model):

    content = models.TextField(blank=True, null=True)
    evaluate = models.ForeignKey(
        Evaluate, on_delete=models.CASCADE, related_name="comments_for_evaluate"
    )
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

blue_chart_app/models/connect.py
from django.db import models
from .cause_tag import CauseTag
from .siteUser import SiteUser


class Connect(models.Model):

    answer = models.ForeignKey(
        "Answer", related_name="connects", on_delete=models.CASCADE
    )
    cause_tag = models.ForeignKey(
        CauseTag, related_name="connects", on_delete=models.CASCADE
    )
    connect_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    latest_connect = models.ForeignKey(
        "LatestConnect", on_delete=models.CASCADE, null=True
    )
    is_overcome = models.BooleanField(null=True)

blue_chart_app/models/correct_situation.py
from django.db import models


class CorrectSituation(models.Model):

    situation = models.CharField(null=True, max_length=100)

    def __str__(self):

        return self.situation

blue_chart_app/models/develop.py
from django.db import models
from .problem import Problem


class Develop(models.Model):

    from_problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="from_develops"
    )
    to_problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="to_develops"
    )

blue_chart_app/models/evaluate.py
from django.db import models
from .evaluation_tag import EvaluationTag
from .siteUser import SiteUser
from .problem import Problem


class Evaluate(models.Model):

    evaluation_tag = models.ForeignKey(
        EvaluationTag, on_delete=models.CASCADE, related_name="by_for_evalution"
    )
    evaluate_user = models.ForeignKey(
        SiteUser, on_delete=models.CASCADE, related_name="by_for_site_user"
    )
    problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="evaluates"
    )

blue_chart_app/models/evaluation_tag.py
from django.db import models
from .type import Type


class EvaluationTag(models.Model):
    
    content = models.CharField(max_length=255, null=True)
    evaluation_type = models.ForeignKey(Type, related_name="evaluation", on_delete=models.CASCADE)

blue_chart_app/models/latest_connect.py
from django.db import models
from .problem import Problem
from .cause_tag import CauseTag
from .siteUser import SiteUser
from .connect import Connect
from django.db.models import Count


class LatestConnect(models.Model):
    
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    cause_tag = models.ForeignKey(CauseTag, related_name="latest_connects", on_delete=models.CASCADE)
    solve_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    connect_model = models.OneToOneField(Connect, on_delete=models.SET_NULL, null=True)
    
    def get_count_of_not_overcome_answer(self):

        count_of_not_overcome_answer = Connect.objects.select_related("latest_connect").filter(is_overcome=False).filter(latest_connect=self).count()

        return count_of_not_overcome_answer

blue_chart_app/models/problem.py
from django.db import models
from .problem_group import Problem_group


class Problem(models.Model):

    name = models.CharField(max_length=50)
    number = models.CharField(max_length=20)
    page = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0)
    problem_group = models.ForeignKey(
        Problem_group, on_delete=models.CASCADE, related_name="problems"
    )

    def __str__(self):

        return self.name

blue_chart_app/models/problem_group.py
from django.db import models
from .section import Section


class Problem_group(models.Model):

    name = models.CharField(max_length=50)
    title = models.CharField(max_length=20, default="")
    number = models.IntegerField(default=0, null=True)
    page = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0, null=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blue_chart_app/models/section.py
from django.db import models
from .chapter import Chapter


class Section(models.Model):

    name = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blue_chart_app/models/similar.py
from django.db import models
from .problem import Problem


class Similar(models.Model):

    from_problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="from_similars",
        null=True,
        default=None,
    )
    to_problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="to_similars",
        null=True,
        default=None,
    )

blue_chart_app/models/siteUser.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class SiteUser(AbstractUser):
    
    is_teacher = models.IntegerField(default=0)
    reference_user = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, default=None
    )

blue_chart_app/models/subject.py
from django.db import models


class Subject(models.Model):

    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

blue_chart_app/templates/comment_for_answer_photo/register.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href = "{% url 'blue_chart_app:chapter_list' %}">
            章一覧
        </a> > 
        <a href="{% url 'blue_chart_app:section_list' answer_photo.answer.problem.problem_group.section.chapter.id %}">
            {{answer_photo.answer.problem.problem_group.section.chapter.subject.name}} 
            第{{answer_photo.answer.problem.problem_group.section.chapter.number}}章 
            {{ answer_photo.answer.problem.problem_group.section.chapter.name }}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_group_list' answer_photo.answer.problem.problem_group.section.id %}"> 
            §{{answer_photo.answer.problem.problem_group.section.number}} 
            {{answer_photo.answer.problem.problem_group.section.name}}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_list' answer_photo.answer.problem.problem_group.id %}">
            {{answer_photo.answer.problem.problem_group.name}}{{answer_photo.answer.problem_group.name}}
            （{{answer_photo.answer.problem.problem_group.problems.all|length}}題）
        </a> > 
        <a href="{% url 'blue_chart_app:problem_show' answer_photo.answer.problem.id %}">
            {{answer_photo.answer.problem.name}}
        </a> > 
        <a href="{% url 'blue_chart_app:answer_list_with_problem' answer_photo.answer.problem.id %}">
            勉強記録一覧
        </a> > 
        <a href="{% url 'blue_chart_app:answer_show' answer_photo.answer.id %}">
            {{answer_photo.answer.solve_plan_date|date:"Y年m月d日"}}
        </a> > 
        解答写真のコメント新規作成
    </p>
    <h2>解答写真のコメント新規作成ページ</h2><br>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>範囲</td>
                <td>{{answer_photo.answer.problem.problem_group.section.chapter.subject.name}} 
                    §{{answer_photo.answer.problem.problem_group.section.number}} 
                    {{answer_photo.answer.problem.problem_group.section.name}}
                </td>
            </tr>
            <tr>
                <td>問題名</td>
                <td>{{answer_photo.answer.problem.name}}</td>
            </tr>
            <tr>
                <td>詳細</td>
                <td>{{answer_photo.answer.problem.problem_group.title}}</td>
            </tr>
            <tr>
                <td>解答予定日</td>
                <td>{{answer_photo.answer.solve_plan_date|date:"Y/m/d H:i"}}</td>
            </tr>
            <tr>
                <td>解答日</td>
                <td>
                    {% if answer_photo.answer.solve_date != None %}
                       {{answer_photo.answer.solve_date|date:"Y/m/d H:i"}}
                    {% else %}
                        ー
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>解答状況</td>
                <td>
                    {{answer_photo.answer.correct_situation.situation}}
                </td>
            </tr>
            <tr>
                <td>解答時間</td>
                <td>
                     {% if answer_photo.answer.actual_time != 0 and answer_photo.answer.actual_time != None %}
                        {{answer_photo.answer.actual_time}}分
                    {% else %}
                        ー
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    <div>
        {% if answer_photo.image.url != '' %}
            <img src="{{answer_photo.image.url}}">
        {% else %}
            写真は削除されました
        {% endif %}
    </div>
    <br>
    <form method="post" action="{% url 'blue_chart_app:comment_for_answer_photo_register' answer_photo.id %}">
        <div class="form-group">
            <label>{{form.content.label}}</label>
            <textarea name="{{form.content.name}}" class="form-control {% if form.content.errors %}is-invalid{% endif %}">{% if form.content.value != None %}{{form.content.value}}{% endif %}</textarea>
            {% if form.content.errors %}
                <div class="invalid-feedback">{{form.content.errors.0}}</div>
            {% endif %}
        </div>
        <br><button class="btn btn-primary" type="submit">登録</button>
        {% csrf_token %}  
    </form>
{% endblock %}

blue_chart_app/templates/comment_for_answer_photo/update.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href = "{% url 'blue_chart_app:chapter_list' %}">
            章一覧
        </a> > 
        <a href="{% url 'blue_chart_app:section_list' comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.chapter.id %}">
            {{comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.chapter.subject.name}} 
            第{{comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.chapter.number}}章 
            {{ comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.chapter.name }}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_group_list' comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.id %}"> 
            §{{comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.number}} 
            {{comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.name}}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_list' comment_for_answer_photo.answer_photo.answer.problem.problem_group.id %}">
            {{comment_for_answer_photo.answer_photo.answer.problem.problem_group.name}}{{comment_for_answer_photo.answer_photo.answer.problem_group.name}}
            （{{comment_for_answer_photo.answer.problem.problem_group.problems.all|length}}題）
        </a> > 
        <a href="{% url 'blue_chart_app:problem_show' comment_for_answer_photo.answer_photo.answer.problem.id %}">
            {{comment_for_answer_photo.answer_photo.answer.problem.name}}
        </a> > 
        <a href="{% url 'blue_chart_app:answer_list_with_problem' comment_for_answer_photo.answer_photo.answer.problem.id %}">
            勉強記録一覧
        </a> > 
        <a href="{% url 'blue_chart_app:answer_show' comment_for_answer_photo.answer_photo.answer.id %}">
            {{comment_for_answer_photo.answer_photo.answer.solve_plan_date|date:"Y年m月d日"}}
        </a> >
        解答写真のコメント編集
    </p>
    <h2>解答写真のコメント編集ページ</h2>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>範囲</td>
                <td>{{comment_for_answer_photo.answer_photo.answer.problem.problem_group.section.chapter.subject.name}}
                    §{{comment_for_answer_photo.answer_photo.answer_photo.answer.problem.problem_group.section.number}} 
                    {{comment_for_answer_photo.answer_photo.answer_photo.answer.problem.problem_group.section.name}}
                </td>
            </tr>
            <tr>
                <td>問題名</td>
                <td>{{comment_for_answer_photo.answer_photo.answer.problem.name}}</td>
            </tr>
            <tr>
                <td>詳細</td>
                <td>{{comment_for_answer_photo.answer_photo.answer.problem.problem_group.title}}</td>
            </tr>
            <tr>
                <td>解答予定日</td>
                <td>{{comment_for_answer_photo.answer_photo.answer.solve_plan_date|date:"Y/m/d H:i"}}</td>
            </tr>
            <tr>
                <td>解答日</td>
                <td>
                    {% if comment_for_answer_photo.answer_photo.answer.solve_date != None %}
                       {{comment_for_answer_photo.answer_photo.answer.solve_date|date:"Y/m/d H:i"}}
                    {% else %}
                        ー
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>解答状況</td>
                <td>
                    {{comment_for_answer_photo.answer_photo.answer.correct_situation.situation}}
                </td>
            </tr>
            <tr>
                <td>解答時間</td>
                <td>
                     {% if comment_for_answer_photo.answer_photo.answer.actual_time != 0 and comment_for_answer_photo.answer_photo.answer.actual_time != None %}
                        {{comment_for_answer_photo.answer_photo.answer.actual_time}}分
                    {% else %}
                        ー
                    {% endif %}
                </td>
            </tr>
    </table>
    <div>
        {% if comment_for_answer_photo.answer_photo.image.url != '' %}
            <img src="{{comment_for_answer_photo.answer_photo.image.url}}">
        {% else %}
            写真は削除されました
        {% endif %}
    </div>
    <br>
    <form method="post" action="{% url 'blue_chart_app:comment_for_answer_photo_update' comment_for_answer_photo.id %}">
        <div class="form-group">
            <label>{{form.content.label}}</label>
            <textarea name="{{form.content.name}}" class="form-control {% if form.content.errors %} is-invalid {% endif %}">{% if form.content.value != None %}{{form.content.value}}{% endif %}</textarea>
            {% if form.content.errors %}
                <div class="invalid-feedback">{{form.content.errors.0}}</div>
            {% endif %}
        </div>
        <br><button class="btn btn-primary" type="submit">登録</button>
   　   {% csrf_token %}  
    </form>
    
{% endblock %}