blue_chart_app/urls.py
"""
Created on Sat Dec 19 13:50:53 2020

@author: Mayuko
"""


from django.urls import path
from . import views


app_name = 'blue_chart_app'

urlpatterns = [
    
    path('', views.chapter_view.chapter_list, name='chapter_list'),
    path('siteUser/register', views.siteUser_view.siteUser_register, name='siteUser_register'),
    path('siteUser/logout', views.siteUser_view.siteUser_logout, name='siteUser_logout'),
    path('siteUser/login', views.siteUser_view.siteUser_login, name='siteUser_login'),
    path('siteUser/reference_user/login', views.siteUser_view.reference_user_login_view, name='reference_user_login'),
    path('siteUser/reference_user/logout', views.siteUser_view.reference_user_logout_view, name='reference_user_logout'),
    path('chapter/list', views.chapter_view.chapter_list, name='chapter_list'),
    path('section/list/<int:chapter_id>/', views.section_view.section_list_view, name='section_list'),
    path('problem_group/list/<int:section_id>/', views.problem_group_view.problem_group_list_view, name='problem_group_list'),
    path('problem/list/<int:problem_group_id>/', views.problem_view.problem_list_view, name='problem_list'),
    path('problem/search', views.problem_view.problem_search_view, name='problem_search'),
    path('problem/show/<int:problem_id>/', views.problem_view.problem_show_view, name='problem_show'),
    path('problem/list_with_cause_tag/<int:cause_tag_id>/<int:section_id>/', views.problem_view.problem_list_with_cause_tag_view, name='problem_list_with_cause_tag'),
    path('evaluate/register/<int:problem_id>/', views.evaluate_view.evaluate_register_view, name='evaluate_register'),
    path('evaluate/delete/<int:evaluate_id>/', views.evaluate_view.evaluate_delte_view, name='evaluate_delete'),
    path('comment_for_evaluate/register/<int:evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_register_view, name='comment_for_evaluate_register'),
    path('comment_for_evaluate/update/<int:comment_for_evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_update_view, name='comment_for_evaluate_update'),
    path('comment_for_evaluate/delte/<int:comment_for_evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_delete_view, name='comment_for_evaluate_delete'),
    path('evaluation/suggest/', views.evaluation_tag_view.evaluation_tag_suggest_view, name='evaluation_tag_suggest'),
    path('evaluation/search/', views.evaluation_tag_view.evaluation_tag_search_view, name='evaluation_tag_search'),
    path('answer/register/<int:problem_id>/', views.answer_view.answer_register_view, name='answer_register'),
    path('answer/update/<int:answer_id>/', views.answer_view.answer_update_view, name='answer_update'),
    path('answer/list_with_problem/<int:problem_id>/', views.answer_view.answer_list_with_problem_view, name='answer_list_with_problem'),
    path('answer/list_with_cause_tag/<int:problem_id>/<int:cause_tag_id>/<int:section_id>/', views.answer_view.answer_list_with_cause_tag_view, name='answer_list_with_cause_tag'),
    path('answer/all_list/', views.answer_view.answer_all_list_view, name='answer_all_list'),
    path('answer/show/<int:answer_id>/', views.answer_view.answer_show_view, name='answer_show'),
    path('answer/delete/<int:answer_id>/', views.answer_view.answer_delete_view, name='answer_delete'),
    path('commet_for_answer/register/<int:answer_id>/', views.comment_for_answer_view.comment_for_answer_register_view, name='comment_for_answer_register'),
    path('comment_for_answer/update/<int:comment_for_answer_id>/', views.comment_for_answer_view.comment_for_answer_update_view, name='comment_for_answer_update'),
    path('comment_for_answer/delete/<int:comment_for_answer_id>/', views.comment_for_answer_view.comment_for_answer_delete_view, name='comment_for_answer_delete'),
    path('answer_photo/register/<int:answer_id>/', views.answer_photo_view.answer_photo_register_view, name='answer_photo_register'),
    path('answer_photo/delete/<int:answer_photo_id>/', views.answer_photo_view.answer_photo_delete_view, name='answer_photo_delete'),
    path('comment_for_answer_photo/register/<int:answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_register_view, name='comment_for_answer_photo_register'),
    path('comment_for_answer_photo/update/<int:comment_for_answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_update_view, name='comment_for_answer_photo_update'),
    path('comment_for_answer_photo/delete/<int:comment_for_answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_delete_view, name='comment_for_answer_photo_delete'),
    path('cause_tag/list/<int:section_id>/', views.cause_tag_view.cause_tag_list_view, name='cause_tag_list'),
    path('cause_tag/graph/', views.cause_tag_view.cause_tag_graph, name='cause_tag_graph'),
    path('cause_tag/connects_count/', views.cause_tag_view.connects_count, name='connects_count'),
    path('connect/register/<int:answer_id>/', views.connect_view.connect_register_view, name='connect_register'),
    path('connect/overcome_flag_change/<int:connect_id>/', views.connect_view.connect_is_overcome_change_view, name='connect_is_overcome_change'),
    path('connect/delete/<int:connect_id>/', views.connect_view.connect_delete_view, name='connect_delete'),
    path('comment_for_connect/register/<int:connect_id>/', views.comment_for_connect_view.comment_for_connect_register_view, name='comment_for_connect_register'),
    path('comment_for_connect/update/<int:comment_for_connect_id>/', views.comment_for_connect_view.comment_for_connect_update_view, name='comment_for_connect_update'),
    path('comemnt_for_connect/delete/<int:comemnt_for_connect_id>/', views.comment_for_connect_view.comment_for_connect_delete_view, name='comment_for_connect_delete'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('blue_chart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

blue_chart_app/models/answer.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .problem import Problem
from .correct_situation import CorrectSituation
from .connect import Connect
from django.core.exceptions import ObjectDoesNotExist


class Answer(models.Model):

    correct_situation = models.ForeignKey(
        CorrectSituation, on_delete=models.CASCADE, null=True
    )
    solve_plan_date = models.DateTimeField(default=timezone.now, blank=True)
    solve_date = models.DateTimeField(default=timezone.now, null=True)
    actual_time = models.IntegerField(null=True)
    student = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def is_overcome_with_cause_tag(self, cause_tag_id):
        try:
            connect = Connect.objects.get(answer__id=id, cause_tag__id=cause_tag_id)
            return connect.is_overcome

        except ObjectDoesNotExist:

            return -1

blue_chart_app/models/answer_photo.py
from django.db import models
from .siteUser import SiteUser
from .answer import Answer
from django.utils import timezone


class AnswerPhoto(models.Model):

    image = models.ImageField(upload_to="images", blank=True, null=True)
    upload_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, related_name="answer_photo"
    )
    uploaded_at = models.DateTimeField(default=timezone.now, null=True)

blue_chart_app/models/cause_tag.py
from django.db import models
from .type import Type


class CauseTag(models.Model):

    content = models.CharField(max_length=255, null=True)
    cause_type = models.ForeignKey(
        Type, related_name="cause", on_delete=models.CASCADE, null=True
    )

blue_chart_app/models/chapter.py
from django.db import models
from .subject import Subject


class Chapter(models.Model):

    name = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blue_chart_app/models/comment_for_answer.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .answer import Answer


class CommentForAnswer(models.Model):

    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, null=True, related_name="comments_for_answer"
    )

blue_chart_app/models/comment_for_answer_photo.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .answer import Answer
from .answer_photo import AnswerPhoto


class CommentForAnswerPhoto(models.Model):
    
    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    answer_photo = models.ForeignKey(AnswerPhoto, on_delete=models.PROTECT, null=True, related_name='comments_for_answer_photo')

blue_chart_app/models/comment_for_connect.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .connect import Connect
from .answer_photo import AnswerPhoto


class CommentForConnect(models.Model):

    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    connect = models.ForeignKey(
        Connect, on_delete=models.CASCADE, related_name="comments_for_connect"
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

blue_chart_app/models/comment_for_evaluate.py
from django.db import models
from .evaluate import Evaluate
from .siteUser import SiteUser
from django.utils import timezone


class CommentForEvaluate(models.Model):

    content = models.TextField(blank=True, null=True)
    evaluate = models.ForeignKey(
        Evaluate, on_delete=models.CASCADE, related_name="comments_for_evaluate"
    )
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

blue_chart_app/models/connect.py
from django.db import models
from .cause_tag import CauseTag
from .siteUser import SiteUser


class Connect(models.Model):

    answer = models.ForeignKey(
        "Answer", related_name="connects", on_delete=models.CASCADE
    )
    cause_tag = models.ForeignKey(
        CauseTag, related_name="connects", on_delete=models.CASCADE
    )
    connect_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    latest_connect = models.ForeignKey(
        "LatestConnect", on_delete=models.CASCADE, null=True
    )
    is_overcome = models.BooleanField(null=True)

blue_chart_app/models/correct_situation.py
from django.db import models


class CorrectSituation(models.Model):

    situation = models.CharField(null=True, max_length=100)

    def __str__(self):

        return self.situation

blue_chart_app/models/develop.py
from django.db import models
from .problem import Problem


class Develop(models.Model):

    from_problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="from_develops"
    )
    to_problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="to_develops"
    )

blue_chart_app/models/evaluate.py
from django.db import models
from .evaluation_tag import EvaluationTag
from .siteUser import SiteUser
from .problem import Problem


class Evaluate(models.Model):

    evaluation_tag = models.ForeignKey(
        EvaluationTag, on_delete=models.CASCADE, related_name="by_for_evalution"
    )
    evaluate_user = models.ForeignKey(
        SiteUser, on_delete=models.CASCADE, related_name="by_for_site_user"
    )
    problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="evaluates"
    )

blue_chart_app/models/evaluation_tag.py
from django.db import models
from .type import Type


class EvaluationTag(models.Model):
    
    content = models.CharField(max_length=255, null=True)
    evaluation_type = models.ForeignKey(Type, related_name="evaluation", on_delete=models.CASCADE)

blue_chart_app/models/latest_connect.py
from django.db import models
from .problem import Problem
from .cause_tag import CauseTag
from .siteUser import SiteUser
from .connect import Connect
from django.db.models import Count


class LatestConnect(models.Model):
    
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    cause_tag = models.ForeignKey(CauseTag, related_name="latest_connects", on_delete=models.CASCADE)
    solve_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    connect_model = models.OneToOneField(Connect, on_delete=models.SET_NULL, null=True)
    
    def get_count_of_not_overcome_answer(self):

        count_of_not_overcome_answer = Connect.objects.select_related("latest_connect").filter(is_overcome=False).filter(latest_connect=self).count()

        return count_of_not_overcome_answer

blue_chart_app/models/problem.py
from django.db import models
from .problem_group import Problem_group


class Problem(models.Model):

    name = models.CharField(max_length=50)
    number = models.CharField(max_length=20)
    page = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0)
    problem_group = models.ForeignKey(
        Problem_group, on_delete=models.CASCADE, related_name="problems"
    )

    def __str__(self):

        return self.name

blue_chart_app/models/problem_group.py
from django.db import models
from .section import Section


class Problem_group(models.Model):

    name = models.CharField(max_length=50)
    title = models.CharField(max_length=20, default="")
    number = models.IntegerField(default=0, null=True)
    page = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0, null=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blue_chart_app/models/section.py
from django.db import models
from .chapter import Chapter


class Section(models.Model):

    name = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blue_chart_app/models/similar.py
from django.db import models
from .problem import Problem


class Similar(models.Model):

    from_problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="from_similars",
        null=True,
        default=None,
    )
    to_problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="to_similars",
        null=True,
        default=None,
    )

blue_chart_app/models/siteUser.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class SiteUser(AbstractUser):
    
    is_teacher = models.IntegerField(default=0)
    reference_user = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, default=None
    )

blue_chart_app/models/subject.py
from django.db import models


class Subject(models.Model):

    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

blue_chart_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<html>
    <head>
        <meta charset="UTF-8">
        <title>BlueChart</title>
        <link rel="stylesheet" href="{% static 'css/blue_chart_app.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <a class="navbar-brand" href="{% url 'blue_chart_app:answer_all_list' %}">JA</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                   <li class="nav-item active">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'blue_chart_app:chapter_list' %}">章一覧 <span class="sr-only">(current)</span></a>
                        {% endif %}    
                    </li>
                    <li class="nav-item active">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'blue_chart_app:problem_search' %}">問題検索 <span class="sr-only">(current)</span></a>
                        {% endif %}    
                    </li>
                    <li class="nav-item active">
                      {% if user.is_authenticated %}
                          <a class="nav-link" href="{% url 'blue_chart_app:cause_tag_list' 0 %}">原因タグ一覧 <span class="sr-only">(current)</span></a>
                      {% endif %}    
                  </li>
                  <li class="nav-item active">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'blue_chart_app:cause_tag_graph'%}">未克服原因タググラフ <span class="sr-only">(current)</span></a>
                    {% endif %}    
                </li>
                  <li class="nav-item active">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="#">{{user.username}} <span class="sr-only">(current)</span></a>
                        {% endif %}    
                 </li>
                  <li class="nav-item active">
                        {% if user.reference_user.id != user.id %}
                            <a class="nav-link" href="#">：{{user.reference_user.username}} <span class="sr-only">(current)</span></a>
                        {% endif %}    
                 </li>
                 <li class="nav-item active">
                    {% if user.is_authenticated and user.is_teacher == 1 %}
                        <a class="nav-link disabled" href="{% url 'blue_chart_app:reference_user_login' %}">Student</a>
                    {% endif %}
                  </li>
                  <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link disabled" href="{% url 'blue_chart_app:siteUser_logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link disabled" href="{% url 'blue_chart_app:siteUser_login' %}">Login</a>
                    {% endif %}
                  </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </div>
            </nav>
        </header>
        <div id="wrapper">
            <div id="main">
                <br>
                   
                    {% for message in messages %}
                    <div class="{% if message.tags %}{{ message.tags}}{% endif %}">
                        {{message}}
                    </div>
                    {% endfor %}
                
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <footer>
        </footer>
    </body>
</html>