blue_chart_app/urls.py
"""
Created on Sat Dec 19 13:50:53 2020

@author: Mayuko
"""


from django.urls import path
from . import views


app_name = 'blue_chart_app'

urlpatterns = [
    
    path('', views.chapter_view.chapter_list, name='chapter_list'),
    path('siteUser/register', views.siteUser_view.siteUser_register, name='siteUser_register'),
    path('siteUser/logout', views.siteUser_view.siteUser_logout, name='siteUser_logout'),
    path('siteUser/login', views.siteUser_view.siteUser_login, name='siteUser_login'),
    path('siteUser/reference_user/login', views.siteUser_view.reference_user_login_view, name='reference_user_login'),
    path('siteUser/reference_user/logout', views.siteUser_view.reference_user_logout_view, name='reference_user_logout'),
    path('chapter/list', views.chapter_view.chapter_list, name='chapter_list'),
    path('section/list/<int:chapter_id>/', views.section_view.section_list_view, name='section_list'),
    path('problem_group/list/<int:section_id>/', views.problem_group_view.problem_group_list_view, name='problem_group_list'),
    path('problem/list/<int:problem_group_id>/', views.problem_view.problem_list_view, name='problem_list'),
    path('problem/search', views.problem_view.problem_search_view, name='problem_search'),
    path('problem/show/<int:problem_id>/', views.problem_view.problem_show_view, name='problem_show'),
    path('problem/list_with_cause_tag/<int:cause_tag_id>/<int:section_id>/', views.problem_view.problem_list_with_cause_tag_view, name='problem_list_with_cause_tag'),
    path('evaluate/register/<int:problem_id>/', views.evaluate_view.evaluate_register_view, name='evaluate_register'),
    path('evaluate/delete/<int:evaluate_id>/', views.evaluate_view.evaluate_delte_view, name='evaluate_delete'),
    path('comment_for_evaluate/register/<int:evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_register_view, name='comment_for_evaluate_register'),
    path('comment_for_evaluate/update/<int:comment_for_evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_update_view, name='comment_for_evaluate_update'),
    path('comment_for_evaluate/delte/<int:comment_for_evaluate_id>/', views.comment_for_evaluate_view.comment_for_evaluate_delete_view, name='comment_for_evaluate_delete'),
    path('evaluation/suggest/', views.evaluation_tag_view.evaluation_tag_suggest_view, name='evaluation_tag_suggest'),
    path('evaluation/search/', views.evaluation_tag_view.evaluation_tag_search_view, name='evaluation_tag_search'),
    path('answer/register/<int:problem_id>/', views.answer_view.answer_register_view, name='answer_register'),
    path('answer/update/<int:answer_id>/', views.answer_view.answer_update_view, name='answer_update'),
    path('answer/list_with_problem/<int:problem_id>/', views.answer_view.answer_list_with_problem_view, name='answer_list_with_problem'),
    path('answer/list_with_cause_tag/<int:problem_id>/<int:cause_tag_id>/<int:section_id>/', views.answer_view.answer_list_with_cause_tag_view, name='answer_list_with_cause_tag'),
    path('answer/all_list/', views.answer_view.answer_all_list_view, name='answer_all_list'),
    path('answer/show/<int:answer_id>/', views.answer_view.answer_show_view, name='answer_show'),
    path('answer/delete/<int:answer_id>/', views.answer_view.answer_delete_view, name='answer_delete'),
    path('commet_for_answer/register/<int:answer_id>/', views.comment_for_answer_view.comment_for_answer_register_view, name='comment_for_answer_register'),
    path('comment_for_answer/update/<int:comment_for_answer_id>/', views.comment_for_answer_view.comment_for_answer_update_view, name='comment_for_answer_update'),
    path('comment_for_answer/delete/<int:comment_for_answer_id>/', views.comment_for_answer_view.comment_for_answer_delete_view, name='comment_for_answer_delete'),
    path('answer_photo/register/<int:answer_id>/', views.answer_photo_view.answer_photo_register_view, name='answer_photo_register'),
    path('answer_photo/delete/<int:answer_photo_id>/', views.answer_photo_view.answer_photo_delete_view, name='answer_photo_delete'),
    path('comment_for_answer_photo/register/<int:answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_register_view, name='comment_for_answer_photo_register'),
    path('comment_for_answer_photo/update/<int:comment_for_answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_update_view, name='comment_for_answer_photo_update'),
    path('comment_for_answer_photo/delete/<int:comment_for_answer_photo_id>/', views.comment_for_answer_photo_view.comment_for_answer_photo_delete_view, name='comment_for_answer_photo_delete'),
    path('cause_tag/list/<int:section_id>/', views.cause_tag_view.cause_tag_list_view, name='cause_tag_list'),
    path('cause_tag/graph/', views.cause_tag_view.cause_tag_graph, name='cause_tag_graph'),
    path('cause_tag/connects_count/', views.cause_tag_view.connects_count, name='connects_count'),
    path('connect/register/<int:answer_id>/', views.connect_view.connect_register_view, name='connect_register'),
    path('connect/overcome_flag_change/<int:connect_id>/', views.connect_view.connect_is_overcome_change_view, name='connect_is_overcome_change'),
    path('connect/delete/<int:connect_id>/', views.connect_view.connect_delete_view, name='connect_delete'),
    path('comment_for_connect/register/<int:connect_id>/', views.comment_for_connect_view.comment_for_connect_register_view, name='comment_for_connect_register'),
    path('comment_for_connect/update/<int:comment_for_connect_id>/', views.comment_for_connect_view.comment_for_connect_update_view, name='comment_for_connect_update'),
    path('comemnt_for_connect/delete/<int:comemnt_for_connect_id>/', views.comment_for_connect_view.comment_for_connect_delete_view, name='comment_for_connect_delete'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('blue_chart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

blue_chart_app/models/answer.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .problem import Problem
from .correct_situation import CorrectSituation
from .connect import Connect
from django.core.exceptions import ObjectDoesNotExist


class Answer(models.Model):

    correct_situation = models.ForeignKey(
        CorrectSituation, on_delete=models.CASCADE, null=True
    )
    solve_plan_date = models.DateTimeField(default=timezone.now, blank=True)
    solve_date = models.DateTimeField(default=timezone.now, null=True)
    actual_time = models.IntegerField(null=True)
    student = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def is_overcome_with_cause_tag(self, cause_tag_id):
        try:
            connect = Connect.objects.get(answer__id=id, cause_tag__id=cause_tag_id)
            return connect.is_overcome

        except ObjectDoesNotExist:

            return -1

blue_chart_app/models/answer_photo.py
from django.db import models
from .siteUser import SiteUser
from .answer import Answer
from django.utils import timezone


class AnswerPhoto(models.Model):

    image = models.ImageField(upload_to="images", blank=True, null=True)
    upload_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, related_name="answer_photo"
    )
    uploaded_at = models.DateTimeField(default=timezone.now, null=True)

blue_chart_app/models/cause_tag.py
from django.db import models
from .type import Type


class CauseTag(models.Model):

    content = models.CharField(max_length=255, null=True)
    cause_type = models.ForeignKey(
        Type, related_name="cause", on_delete=models.CASCADE, null=True
    )

blue_chart_app/models/chapter.py
from django.db import models
from .subject import Subject


class Chapter(models.Model):

    name = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blue_chart_app/models/comment_for_answer.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .answer import Answer


class CommentForAnswer(models.Model):

    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, null=True, related_name="comments_for_answer"
    )

blue_chart_app/models/comment_for_answer_photo.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .answer import Answer
from .answer_photo import AnswerPhoto


class CommentForAnswerPhoto(models.Model):
    
    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    answer_photo = models.ForeignKey(AnswerPhoto, on_delete=models.PROTECT, null=True, related_name='comments_for_answer_photo')

blue_chart_app/models/comment_for_connect.py
from django.db import models
from django.utils import timezone
from .siteUser import SiteUser
from .connect import Connect
from .answer_photo import AnswerPhoto


class CommentForConnect(models.Model):

    content = models.TextField(blank=True, null=True)
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    connect = models.ForeignKey(
        Connect, on_delete=models.CASCADE, related_name="comments_for_connect"
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

blue_chart_app/models/comment_for_evaluate.py
from django.db import models
from .evaluate import Evaluate
from .siteUser import SiteUser
from django.utils import timezone


class CommentForEvaluate(models.Model):

    content = models.TextField(blank=True, null=True)
    evaluate = models.ForeignKey(
        Evaluate, on_delete=models.CASCADE, related_name="comments_for_evaluate"
    )
    comment_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

blue_chart_app/models/connect.py
from django.db import models
from .cause_tag import CauseTag
from .siteUser import SiteUser


class Connect(models.Model):

    answer = models.ForeignKey(
        "Answer", related_name="connects", on_delete=models.CASCADE
    )
    cause_tag = models.ForeignKey(
        CauseTag, related_name="connects", on_delete=models.CASCADE
    )
    connect_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    latest_connect = models.ForeignKey(
        "LatestConnect", on_delete=models.CASCADE, null=True
    )
    is_overcome = models.BooleanField(null=True)

blue_chart_app/models/correct_situation.py
from django.db import models


class CorrectSituation(models.Model):

    situation = models.CharField(null=True, max_length=100)

    def __str__(self):

        return self.situation

blue_chart_app/models/develop.py
from django.db import models
from .problem import Problem


class Develop(models.Model):

    from_problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="from_develops"
    )
    to_problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="to_develops"
    )

blue_chart_app/models/evaluate.py
from django.db import models
from .evaluation_tag import EvaluationTag
from .siteUser import SiteUser
from .problem import Problem


class Evaluate(models.Model):

    evaluation_tag = models.ForeignKey(
        EvaluationTag, on_delete=models.CASCADE, related_name="by_for_evalution"
    )
    evaluate_user = models.ForeignKey(
        SiteUser, on_delete=models.CASCADE, related_name="by_for_site_user"
    )
    problem = models.ForeignKey(
        Problem, on_delete=models.CASCADE, related_name="evaluates"
    )

blue_chart_app/models/evaluation_tag.py
from django.db import models
from .type import Type


class EvaluationTag(models.Model):
    
    content = models.CharField(max_length=255, null=True)
    evaluation_type = models.ForeignKey(Type, related_name="evaluation", on_delete=models.CASCADE)

blue_chart_app/models/latest_connect.py
from django.db import models
from .problem import Problem
from .cause_tag import CauseTag
from .siteUser import SiteUser
from .connect import Connect
from django.db.models import Count


class LatestConnect(models.Model):
    
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    cause_tag = models.ForeignKey(CauseTag, related_name="latest_connects", on_delete=models.CASCADE)
    solve_user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    connect_model = models.OneToOneField(Connect, on_delete=models.SET_NULL, null=True)
    
    def get_count_of_not_overcome_answer(self):

        count_of_not_overcome_answer = Connect.objects.select_related("latest_connect").filter(is_overcome=False).filter(latest_connect=self).count()

        return count_of_not_overcome_answer

blue_chart_app/models/problem.py
from django.db import models
from .problem_group import Problem_group


class Problem(models.Model):

    name = models.CharField(max_length=50)
    number = models.CharField(max_length=20)
    page = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0)
    problem_group = models.ForeignKey(
        Problem_group, on_delete=models.CASCADE, related_name="problems"
    )

    def __str__(self):

        return self.name

blue_chart_app/models/problem_group.py
from django.db import models
from .section import Section


class Problem_group(models.Model):

    name = models.CharField(max_length=50)
    title = models.CharField(max_length=20, default="")
    number = models.IntegerField(default=0, null=True)
    page = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0, null=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blue_chart_app/models/section.py
from django.db import models
from .chapter import Chapter


class Section(models.Model):

    name = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

blue_chart_app/models/similar.py
from django.db import models
from .problem import Problem


class Similar(models.Model):

    from_problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="from_similars",
        null=True,
        default=None,
    )
    to_problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="to_similars",
        null=True,
        default=None,
    )

blue_chart_app/models/siteUser.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class SiteUser(AbstractUser):
    
    is_teacher = models.IntegerField(default=0)
    reference_user = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, default=None
    )

blue_chart_app/models/subject.py
from django.db import models


class Subject(models.Model):

    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

blue_chart_app/templates/problem/list.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href = "{% url 'blue_chart_app:chapter_list' %}">
            章一覧
        </a> > 
        <a href="{% url 'blue_chart_app:section_list' problem_group.section.chapter.id %}">
            {{problem_group.section.chapter.subject.name}} 
            第{{problem_group.section.chapter.number}}章 
            {{ problem_group.section.chapter.name }}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_group_list' problem_group.section.id %}"> 
            §{{problem_group.section.number}} {{problem_group.section.name}}
        </a> > 
        {{problem_group.name}}（{{problem_group.problems.all|length}}題）
    </p>
    <table class="table table-striped">
        <tbody>
            {% for problem in problems %}
                <tr>
                    <td>{{ problem.name }}</td>
                    <td><a href="{% url 'blue_chart_app:problem_show' problem.id %}">詳細を見る</a></td>
                </tr>
            {% endfor %}
        
        </tbody>
    </table>
{% endblock %}
    

blue_chart_app/templates/problem/list_with_cause_tag.html
{% extends "base.html" %}
{% block content %}
    <p>
        {% if section is not None %}
            <a href="{% url 'blue_chart_app:cause_tag_list' section.id %}">
                「{{section.name}}」の原因タグ一覧
            </a> > 
        {% else %}
            <a href="{% url 'blue_chart_app:cause_tag_list' 0 %}">
                原因タグ一覧
            </a> > 
        {% endif %}
        原因タグ「{{latest_connects_with_cause_tag.0.cause_tag.content}}」
    </p>
    <h2>原因タグ「{{latest_connects_with_cause_tag.0.cause_tag.content}}」がついている問題一覧</h2>
    <table class="table table-striped">
        <tbody>
            {% for latest_connect in latest_connects_with_cause_tag %}
                <tr>
                    <td>{{latest_connect.problem.problem_group.section.chapter.subject.name}}
                    <td>§{{latest_connect.problem.problem_group.section.number}}</td>
                    <td>{{latest_connect.problem.name }}</td>
                    <td><a href="{% url 'blue_chart_app:problem_show' latest_connect.problem.id %}">問題詳細を見る</a></td>
                    <td>
                        {% if latest_connect.connect_model.is_overcome == 1 %}
                            克服
                        {% else %}
                            未克服
                        {% endif %}
                    </td>
                    <td>
                        {% if section %}
                            <a href="{% url 'blue_chart_app:answer_list_with_cause_tag' latest_connect.problem.id latest_connect.cause_tag.id section.id %}">
                                {{latest_connect.get_count_of_not_overcome_answer}}件の間違い
                            </a>
                        {% else %}
                            <a href="{% url 'blue_chart_app:answer_list_with_cause_tag' latest_connect.problem.id latest_connect.cause_tag.id 0 %}">
                                {{latest_connect.get_count_of_not_overcome_answer}}件の間違い
                            </a>
                        {% endif %}
                    </td>
                </tr> 
                
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

blue_chart_app/templates/problem/show.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href = "{% url 'blue_chart_app:chapter_list' %}">
            章一覧
        </a> > 
        <a href="{% url 'blue_chart_app:section_list' problem.problem_group.section.chapter.id %}">
            {{problem.problem_group.section.chapter.subject.name}} 第{{problem.problem_group.section.chapter.number}}章 {{ problem.problem_group.section.chapter.name }}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_group_list' problem.problem_group.section.id %}">
            §{{problem.problem_group.section.number}} {{problem.problem_group.section.name}}
        </a> > 
        <a href="{% url 'blue_chart_app:problem_list' problem.problem_group.id %}">
            {{problem.problem_group.name}}{{problem_group.name}}（{{problem.problem_group.problems.all|length}}題）
        </a> > 
        {{problem.name}}
    </p>
    <h2>{{problem.name}}の詳細ページ</h2><br>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>範囲</td>
                <td>{{problem.problem_group.section.chapter.subject.name}} §{{problem.problem_group.section.number}} {{problem.problem_group.section.name}}</td>
            </tr>
            <tr>
                <td>問題名</td>
                <td>{{problem.name}}</td>
            </tr>
            <tr>
                <td>詳細</td>
                <td>
                    {% if problem.problem_group.number > 0 %}
                        {{problem.problem_group.title}}
                    {% else %}
                        ー
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    <p class="index">類似問題</p>
    {% if problem.from_similars.all|length != 0 or problem.to_similars.all|length != 0 %}
        {% for fs in problem.from_similars.all %}
            
            {% if fs.to_problem.problem_group.number < 0 %}
                <a href="{% url 'blue_chart_app:problem_show' fs.to_problem.id %}">
                    {{fs.to_problem.problem_group.section.chapter.subject.name}} §{{fs.to_problem.problem_group.section.number}} {{fs.to_problem.name}}
                </a>&nbsp;
            {% else %}
                <a href="{% url 'blue_chart_app:problem_show' fs.to_problem.id %}">{{fs.to_problem.name}}</a>&nbsp;
            {% endif %}
        {% endfor %}
        {% for ts in problem.to_similars.all %}
            {% if ts.from_problem.problem_group.number < 0 %}
                <a href="{% url 'blue_chart_app:problem_show' ts.from_problem.id %}">
                    {{ts.from_problem.problem_group.section.chapter.subject.name}} §{{ts.from_problem.problem_group.section.number}} {{ts.from_problem.name}}
                </a>&nbsp;
            {% else %}
                <a href="{% url 'blue_chart_app:problem_show' ts.from_problem.id %}">{{ts.from_problem.name}}</a>&nbsp;
            {% endif %}
        {% endfor %}
    {% else %}
        なし
    {% endif %}
    <p class="index">基礎問題</p>
    {% if problem.to_develops.all|length != 0 %}
        {% for td in problem.to_develops.all %}
            {% if develop.from_problem.problem_group.number < 0 %}
                <a href="{% url 'blue_chart_app:problem_show' td.from_problem.id %}">
                    {{td.from_problem.problem_group.section.chapter.subject.name}} §{{td.from_problem.problem_group.section.number}} {{td.from_problem.name}}
                </a>&nbsp;
            {% else %}
                <a href="{% url 'blue_chart_app:problem_show' td.from_problem.id %}">{{td.from_problem.name}}</a>&nbsp;
            {% endif %}
        {% endfor %}
    {% else %}
        なし
    {% endif %}
    <p class="index">発展問題</p>
    {% if problem.from_develops.all|length != 0 %}
        {% for fd in problem.from_develops.all %}
            {% if fd.to_problem.problem_group.number < 0 %}
                <a href="{% url 'blue_chart_app:problem_show' fd.to_problem.id %}">
                    {{fd.to_problem.problem_group.section.chapter.subject.name}} §{{fd.to_problem.problem_group.section.number}} {{fd.to_problem.name}}
                </a>&nbsp;
            {% else %}
                <a href="{% url 'blue_chart_app:problem_show' fd.to_problem.id %}">{{fd.to_problem.name}}</a>&nbsp;
            {% endif %}
        {% endfor %}
    {% else %}
        なし
    {% endif %}
    <br>
    <p><a href="{% url 'blue_chart_app:answer_list_with_problem' problem.id %}">勉強記録一覧を見る</a></p>
    <p class="index">評価タグ</p>
    <p><a href="{% url 'blue_chart_app:evaluate_register' problem.id %}">評価タグを登録する</a></p>
    {% if problem.evaluates.all|length != 0 %}
        {% for ev in problem.evaluates.all %}
            <div>
                <span class="tag tag_type{{ev.evaluation_tag.evaluation_type.id}}">
                    {{ev.evaluation_tag.content}}
                </span>
                &nbsp;&nbsp;
                {% if request.user.id == ev.evaluate_user.id %}
                    <a  class="delete" href="#" onclick="confirmDestroy({{ev.id}},'evaluate')">取り消し</a>
                    <form id="form_evaluate_{{ev.id}}" method="post" action="{% url 'blue_chart_app:evaluate_delete' ev.id %}">
                        {% csrf_token %}
                    </form>
                {% endif %}
            </div>
            <span class="evaluation_tag_evaluate_user">{{ev.evaluate_user.username}}</span>
            {% if ev.comments_for_evaluate.all|length == 0 %}
                <div class="explain">
                    <div><a href="{% url 'blue_chart_app:comment_for_evaluate_register' ev.id %}">この評価タグへのコメントを追加する</a></div>
                </div>
            {% else %}
                <div class="explain">
                    <div>{{ev.comments_for_evaluate.all|length}}件のコメント&nbsp;<i id="bar_evaluate{{ev.id}}" class="comment_for_evaluate fas fa-chevron-down"></i></div> 
                </div>
                <div class="comment_for_evaluate" id="comment_for_evaluate{{ev.id}}">
                    <p><a href="{% url 'blue_chart_app:comment_for_evaluate_register' ev.id %}">この評価タグへのコメントを追加する</a></p>
                    <table class="table table-bordered">
                        {% for comment_for_evaluate in ev.comments_for_evaluate.all %}
                            <tr>
                                <td>
                                    <span class="comment_username">{{comment_for_evaluate.comment_user.username}}</span>
                                    &nbsp;&nbsp;{{comment_for_evaluate.updated_at|date:"Y/m/d H:i"}}
                                    {% if comment_for_evaluate.updated_at != comment_for_evaluate.created_at %} (編集済み）{% endif %}
                                    {% if request.user.id == comment_for_evaluate.comment_user.id %}
                                        &nbsp;<a href="{% url 'blue_chart_app:comment_for_evaluate_update' comment_for_evaluate.id %}">編集</a>
                                        &nbsp;&nbsp;<a  class="delete" href="#" onclick="confirmDestroy({{comment_for_evaluate.id}},'evaluate_comment')">削除</a>
                                        <form id="form_evaluate_comment_{{comment_for_evaluate.id}}" method="post" action="{% url 'blue_chart_app:comment_for_evaluate_delete' comment_for_evaluate.id %}">
                                            {% csrf_token %}
                                        </form>
                                    {% endif %}
                                    <br>
                                    {{comment_for_evaluate.content|linebreaksbr}} 
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endif %}
            <br><hr>
        {% endfor %}
    {% else %}
        評価タグはまだありません
    {% endif %}
    <script>
        $('.comment_for_evaluate').on('click', (e) => {
          
           id = '#' + e.target.id
           comment_for_evaluate_id = id.replace('bar_evaluate', 'comment_for_evaluate')
           target_class = ''
           
           if (e.target.className == 'comment_for_evaluate fas fa-chevron-down') {
               target_class = 'wcomment_for_evaluate fas fa-chevron-up'
               $(comment_for_evaluate_id).show()
           } else {
               target_class = 'comment_for_evaluate fas fa-chevron-down'
               $(comment_for_evaluate_id).hide()
           }
           
          
           $(id).attr('class', target_class)
       
       });

       function confirmDestroy(id, type) {
            if(confirm("本当に削除してよろしいですか？")) {
                id = 'form_'+type+'_'+id;
                form = document.getElementById(id)
                
                form.submit();                
            }
        }

    </script>
    
    
{% endblock %}